const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL : 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START:'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS:"FETCH_GENDER_SUCCESS",
    FETCH_GENDER_FAIDED:'FETCH_GENDER_FAIDED',

    FETCH_POSITION_SUCCESS:"FETCH_POSITION_SUCCESS",
    FETCH_POSITION_FAIDED:'FETCH_POSITION_FAIDED',

    FETCH_ROLE_SUCCESS:"FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAIDED:'FETCH_ROLE_FAIDED',

    CREATE_USER_SUCCESS:'SAVE_USER_SUCCESS',
    CREATE_USER_FAILED:'SAVE_USER_FAILED',

    FETCH_ALL_USER_SUCCESS:'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED:'FETCH_ALL_USER_FAILED',

    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED:'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED:'EDIT_USER_FAILED',

    FETCH_TOP_DOCTOR_SUCCESS:'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILED:'FETCH_TOP_DOCTOR_FAILED',

    FETCH_ALL_DOCTOR_SUCCESS:'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED:'FETCH_ALL_DOCTOR_FAILED',

    SAVE_DETAILE_DOCTOR_SUCCESS:'SAVE_DETAILE_DOCTOR_SUCCESS',
    SAVE_DETAILE_DOCTOR_FAILED:'SAVE_DETAILE_DOCTOR_FAILED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',

    FETCH_REQUIRE_DOCTOR_INFO_START:'FETCH_REQUIRE_DOCTOR_INFO_START',
    FETCH_REQUIRE_DOCTOR_INFO_SUCCESS:'FETCH_REQUIRE_DOCTOR_INFO_SUCCESS',
    FETCH_REQUIRE_DOCTOR_INFO_FAIDED:'FETCH_REQUIRE_DOCTOR_INFO_FAIDED'
})


export default actionTypes;